<a href="https://colab.research.google.com/github/CallmeQuita/SIC/blob/main/Chapter%208/Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Một số hàm xử lý trên Tensor

In [ ]:
import tensorflow as tf

In [ ]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())
t_splits = tf.split(t,3)
[item.numpy() for item in t_splits]

[0.16513085 0.9014813  0.6309742  0.4345461  0.29193902 0.64250207]


[array([0.16513085, 0.9014813 ], dtype=float32),
 array([0.6309742, 0.4345461], dtype=float32),
 array([0.29193902, 0.64250207], dtype=float32)]

In [ ]:
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A,B],axis=0)
print(C.numpy())

[1. 1. 1. 0. 0.]


In [ ]:
A = tf.ones((3,))
B = tf.zeros((3,))
S = tf.stack([A,B],axis=1)
print(S.numpy())

[[1. 0.]
 [1. 0.]
 [1. 0.]]


In [ ]:
a = [1.2,3.4,7.5,4.1,5.0,1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>


In [ ]:
for item in ds:
  print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch,100):
  print('batch {}:'.format(i),elem.numpy())

batch 100: [1.2 3.4 7.5]
batch 101: [4.1 5.  1. ]


## Join 2 tensor

In [ ]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4,3],dtype=tf.float32)
t_y = tf.range(4)
print(t_x)
print(t_y)

tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]
 [0.60489583 0.6366315  0.6144488 ]], shape=(4, 3), dtype=float32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [ ]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)
ds_joint = tf.data.Dataset.zip((ds_x,ds_y))
for item in ds_joint:
  print(' x:', item[0].numpy(),
        ' y:',item[1].numpy())

 x: [0.16513085 0.9014813  0.6309742 ]  y: 0
 x: [0.4345461  0.29193902 0.64250207]  y: 1
 x: [0.9757855  0.43509948 0.6601019 ]  y: 2
 x: [0.60489583 0.6366315  0.6144488 ]  y: 3


In [ ]:
ds_trans = ds_joint.map(lambda x,y:(x*2-1.0,y))
for item in ds_trans:
  print(' x:', item[0].numpy(),
        ' y:',item[1].numpy())

 x: [-0.6697383   0.80296254  0.26194835]  y: 0
 x: [-0.13090777 -0.41612196  0.28500414]  y: 1
 x: [ 0.951571   -0.12980103  0.32020378]  y: 2
 x: [0.20979166 0.27326298 0.22889757]  y: 3


## shuffle(), batch(), repeat()

In [ ]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(buffer_size=len(t_x))
for e in ds:
  print(' x:', e[0].numpy(),
        ' y:',e[1].numpy())

 x: [0.9757855  0.43509948 0.6601019 ]  y: 2
 x: [0.4345461  0.29193902 0.64250207]  y: 1
 x: [0.16513085 0.9014813  0.6309742 ]  y: 0
 x: [0.60489583 0.6366315  0.6144488 ]  y: 3


In [ ]:
ds = ds_joint.batch(batch_size=3,drop_remainder=False)
batch_x,batch_y = next(iter(ds))
print('batch x:\n',batch_x.numpy())
print('batch y:\n',batch_y.numpy())

batch x:
 [[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]]
batch y:
 [0 1 2]


In [ ]:
ds = ds_joint.batch(3).repeat(count=2)
for i,(batch_x,batch_y) in enumerate(ds):
  print(i,batch_x.numpy(),batch_y.numpy())

0 [[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]] [0 1 2]
1 [[0.60489583 0.6366315  0.6144488 ]] [3]
2 [[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]] [0 1 2]
3 [[0.60489583 0.6366315  0.6144488 ]] [3]


In [ ]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(4).batch(2).repeat(20)
for i,(batch_x,batch_y) in enumerate(ds):
  print(i,batch_x.numpy(),batch_y.numpy())

0 [[0.9757855  0.43509948 0.6601019 ]
 [0.4345461  0.29193902 0.64250207]] [2 1]
1 [[0.16513085 0.9014813  0.6309742 ]
 [0.60489583 0.6366315  0.6144488 ]] [0 3]
2 [[0.16513085 0.9014813  0.6309742 ]
 [0.60489583 0.6366315  0.6144488 ]] [0 3]
3 [[0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]] [1 2]
4 [[0.60489583 0.6366315  0.6144488 ]
 [0.16513085 0.9014813  0.6309742 ]] [3 0]
5 [[0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]] [1 2]
6 [[0.4345461  0.29193902 0.64250207]
 [0.60489583 0.6366315  0.6144488 ]] [1 3]
7 [[0.9757855  0.43509948 0.6601019 ]
 [0.16513085 0.9014813  0.6309742 ]] [2 0]
8 [[0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]] [1 2]
9 [[0.60489583 0.6366315  0.6144488 ]
 [0.16513085 0.9014813  0.6309742 ]] [3 0]
10 [[0.60489583 0.6366315  0.6144488 ]
 [0.16513085 0.9014813  0.6309742 ]] [3 0]
11 [[0.9757855  0.43509948 0.6601019 ]
 [0.4345461  0.29193902 0.64250207]] [2 1]
12 [[0.60489583 0.6366315 